#!/bin/bash
# Script pour push sécurisé

echo "🚀 Instructions pour le push final"
echo ""
echo "Ce script va remplacer COMPLETEMENT l'historique sur GitHub."
echo "C'est nécessaire pour supprimer les clés exposées."
echo ""
echo "Commandes à exécuter :"
echo ""
echo "Option 1 - Si vous avez les droits d'accès :"
echo "  git push origin main --force"
echo ""
echo "Option 2 - Si vous devez vous authentifier :"
echo "  git push https://USERNAME:TOKEN@github.com/ErwanHenry/kaspa-ecosystem.git main --force"
echo ""
echo "Option 3 - Avec GitHub CLI (si installé) :"
echo "  gh auth login"
echo "  git push origin main --force"
echo ""
echo "Option 4 - Si le repo est protégé :"
echo "  1. Allez sur GitHub > Settings > Branches"
echo "  2. Désactivez temporairement la protection de branche"
echo "  3. Faites le push --force"
echo "  4. Réactivez la protection"
echo ""
echo "⚠️  Si vous avez une erreur 403 :"
echo "  - Vérifiez vos droits sur le repo"
echo "  - Créez un Personal Access Token sur GitHub"
echo "  - Utilisez l'Option 2 avec votre token"
